export const ALL_BOOKS = [
  // Old Testament
  { name: 'Genesis', abbr: 'Gen', chapters: 50, category: 'Old Testament', section: 'Pentateuch' },
  { name: 'Exodus', abbr: 'Exo', chapters: 40, category: 'Old Testament', section: 'Pentateuch' },
  { name: 'Leviticus', abbr: 'Lev', chapters: 27, category: 'Old Testament', section: 'Pentateuch' },
  { name: 'Numbers', abbr: 'Num', chapters: 36, category: 'Old Testament', section: 'Pentateuch' },
  { name: 'Deuteronomy', abbr: 'Deu', chapters: 34, category: 'Old Testament', section: 'Pentateuch' },
  { name: 'Joshua', abbr: 'Jos', chapters: 24, category: 'Old Testament', section: 'History' },
  { name: 'Judges', abbr: 'Jdg', chapters: 21, category: 'Old Testament', section: 'History' },
  { name: 'Ruth', abbr: 'Rut', chapters: 4, category: 'Old Testament', section: 'History' },
  { name: '1 Samuel', abbr: '1Sa', chapters: 31, category: 'Old Testament', section: 'History' },
  { name: '2 Samuel', abbr: '2Sa', chapters: 24, category: 'Old Testament', section: 'History' },
  { name: '1 Kings', abbr: '1Ki', chapters: 22, category: 'Old Testament', section: 'History' },
  { name: '2 Kings', abbr: '2Ki', chapters: 25, category: 'Old Testament', section: 'History' },
  { name: '1 Chronicles', abbr: '1Ch', chapters: 29, category: 'Old Testament', section: 'History' },
  { name: '2 Chronicles', abbr: '2Ch', chapters: 36, category: 'Old Testament', section: 'History' },
  { name: 'Ezra', abbr: 'Ezr', chapters: 10, category: 'Old Testament', section: 'History' },
  { name: 'Nehemiah', abbr: 'Neh', chapters: 13, category: 'Old Testament', section: 'History' },
  { name: 'Esther', abbr: 'Est', chapters: 10, category: 'Old Testament', section: 'History' },
  { name: 'Job', abbr: 'Job', chapters: 42, category: 'Old Testament', section: 'Wisdom' },
  { name: 'Psalms', abbr: 'Psa', chapters: 150, category: 'Old Testament', section: 'Wisdom' },
  { name: 'Proverbs', abbr: 'Pro', chapters: 31, category: 'Old Testament', section: 'Wisdom' },
  { name: 'Ecclesiastes', abbr: 'Ecc', chapters: 12, category: 'Old Testament', section: 'Wisdom' },
  { name: 'Song of Solomon', abbr: 'Son', chapters: 8, category: 'Old Testament', section: 'Wisdom' },
  { name: 'Isaiah', abbr: 'Isa', chapters: 66, category: 'Old Testament', section: 'Major Prophets' },
  { name: 'Jeremiah', abbr: 'Jer', chapters: 52, category: 'Old Testament', section: 'Major Prophets' },
  { name: 'Lamentations', abbr: 'Lam', chapters: 5, category: 'Old Testament', section: 'Major Prophets' },
  { name: 'Ezekiel', abbr: 'Eze', chapters: 48, category: 'Old Testament', section: 'Major Prophets' },
  { name: 'Daniel', abbr: 'Dan', chapters: 12, category: 'Old Testament', section: 'Major Prophets' },
  { name: 'Hosea', abbr: 'Hos', chapters: 14, category: 'Old Testament', section: 'Minor Prophets' },
  { name: 'Joel', abbr: 'Joe', chapters: 3, category: 'Old Testament', section: 'Minor Prophets' },
  { name: 'Amos', abbr: 'Amo', chapters: 9, category: 'Old Testament', section: 'Minor Prophets' },
  { name: 'Obadiah', abbr: 'Oba', chapters: 1, category: 'Old Testament', section: 'Minor Prophets' },
  { name: 'Jonah', abbr: 'Jon', chapters: 4, category: 'Old Testament', section: 'Minor Prophets' },
  { name: 'Micah', abbr: 'Mic', chapters: 7, category: 'Old Testament', section: 'Minor Prophets' },
  { name: 'Nahum', abbr: 'Nah', chapters: 3, category: 'Old Testament', section: 'Minor Prophets' },
  { name: 'Habakkuk', abbr: 'Hab', chapters: 3, category: 'Old Testament', section: 'Minor Prophets' },
  { name: 'Zephaniah', abbr: 'Zep', chapters: 3, category: 'Old Testament', section: 'Minor Prophets' },
  { name: 'Haggai', abbr: 'Hag', chapters: 2, category: 'Old Testament', section: 'Minor Prophets' },
  { name: 'Zechariah', abbr: 'Zec', chapters: 14, category: 'Old Testament', section: 'Minor Prophets' },
  { name: 'Malachi', abbr: 'Mal', chapters: 4, category: 'Old Testament', section: 'Minor Prophets' },
  // New Testament
  { name: 'Matthew', abbr: 'Mat', chapters: 28, category: 'New Testament', section: 'Gospels' },
  { name: 'Mark', abbr: 'Mar', chapters: 16, category: 'New Testament', section: 'Gospels' },
  { name: 'Luke', abbr: 'Luk', chapters: 24, category: 'New Testament', section: 'Gospels' },
  { name: 'John', abbr: 'Joh', chapters: 21, category: 'New Testament', section: 'Gospels' },
  { name: 'Acts', abbr: 'Act', chapters: 28, category: 'New Testament', section: 'History' },
  { name: 'Romans', abbr: 'Rom', chapters: 16, category: 'New Testament', section: 'Epistles' },
  { name: '1 Corinthians', abbr: '1Co', chapters: 16, category: 'New Testament', section: 'Epistles' },
  { name: '2 Corinthians', abbr: '2Co', chapters: 13, category: 'New Testament', section: 'Epistles' },
  { name: 'Galatians', abbr: 'Gal', chapters: 6, category: 'New Testament', section: 'Epistles' },
  { name: 'Ephesians', abbr: 'Eph', chapters: 6, category: 'New Testament', section: 'Epistles' },
  { name: 'Philippians', abbr: 'Phi', chapters: 4, category: 'New Testament', section: 'Epistles' },
  { name: 'Colossians', abbr: 'Col', chapters: 4, category: 'New Testament', section: 'Epistles' },
  { name: '1 Thessalonians', abbr: '1Th', chapters: 5, category: 'New Testament', section: 'Epistles' },
  { name: '2 Thessalonians', abbr: '2Th', chapters: 3, category: 'New Testament', section: 'Epistles' },
  { name: '1 Timothy', abbr: '1Ti', chapters: 6, category: 'New Testament', section: 'Epistles' },
  { name: '2 Timothy', abbr: '2Ti', chapters: 4, category: 'New Testament', section: 'Epistles' },
  { name: 'Titus', abbr: 'Tit', chapters: 3, category: 'New Testament', section: 'Epistles' },
  { name: 'Philemon', abbr: 'Phm', chapters: 1, category: 'New Testament', section: 'Epistles' },
  { name: 'Hebrews', abbr: 'Heb', chapters: 13, category: 'New Testament', section: 'Epistles' },
  { name: 'James', abbr: 'Jam', chapters: 5, category: 'New Testament', section: 'Epistles' },
  { name: '1 Peter', abbr: '1Pe', chapters: 5, category: 'New Testament', section: 'Epistles' },
  { name: '2 Peter', abbr: '2Pe', chapters: 3, category: 'New Testament', section: 'Epistles' },
  { name: '1 John', abbr: '1Jo', chapters: 5, category: 'New Testament', section: 'Epistles' },
  { name: '2 John', abbr: '2Jo', chapters: 1, category: 'New Testament', section: 'Epistles' },
  { name: '3 John', abbr: '3Jo', chapters: 1, category: 'New Testament', section: 'Epistles' },
  { name: 'Jude', abbr: 'Jud', chapters: 1, category: 'New Testament', section: 'Epistles' },
  { name: 'Revelation', abbr: 'Rev', chapters: 22, category: 'New Testament', section: 'Prophecy' },
];

export const TRANSLATIONS = [
  { code: 'AMP',  name: 'Amplified Bible',         year: '2015', id: 'a81b73293d3080c9-01' },
  { code: 'NKJV', name: 'New King James Version',  year: '1982', id: '63097d2a0a2f7db3-01' },
  { code: 'NIV',  name: 'New International Version',year: '1978', id: '78a9f6124f344018-01' },
  { code: 'MSG',  name: 'The Message',              year: '2002', id: '6f11a7de016f942e-01' },
  { code: 'NLT',  name: 'New Living Translation',   year: '1996', id: 'd6e14a625393b4da-01' },
  { code: 'KJV',  name: 'King James Version',       year: '1611', id: 'de4e12af7f28f599-01' },
];

export const OLD_TESTAMENT_SECTIONS = ['Pentateuch', 'History', 'Wisdom', 'Major Prophets', 'Minor Prophets'];
export const NEW_TESTAMENT_SECTIONS = ['Gospels', 'History', 'Epistles', 'Prophecy'];